packages:
  - "packages/*"
  - "apps/*"

catalogs:
  default:
    next: 16.0.7
    rollup: ^4.53.3
    rollup-plugin-esbuild: ^6.2.1
    rollup-plugin-node-externals: ^8.1.2
    "@rollup/plugin-replace": ^6.0.3
    "@rollup/plugin-typescript": ^12.3.0
